### ISSUE TITLE
Important Message

### ISSUE THREAD

**Issue by Alexis12119** [adityastomar67/NvStar#1]
Hi, I just want to say that I made some updates in `dull` and It would be great if you will put a comment of my config link in the top of this [file](https://github.com/adityastomar67/NvStar/blob/main/colors/dull.lua)  as credits, since my repo doesn't have license. Here are the latest [highlights](https://github.com/Alexis12119/nvim-config/blob/master/lua/user/theme/highlights.lua) and [palette](https://github.com/Alexis12119/nvim-config/blob/master/lua/user/theme/palette.lua). That's all and thanks for including my made from scratch colorscheme even it's not that organized and good.

**Comment by adityastomar67** [comment]
Done...btw looking for more inspirations like this...
