### ISSUE TITLE
Packer not installing plugins

### ISSUE THREAD

**Issue by esperaking81** [adityastomar67/NvStar#2]
Hello !
I'm trying out your configs. But packer isn't installing plugins.
Seems like the init.lua file is not recognized.
Is there a special requirement needed for the file structure in the nvim folder ?

**Comment by adityastomar67** [comment]
Is it showing some sort of error or misbehaviour. If you can put some more details or screenshot, then I can help you more easily.

**Comment by esperaking81** [comment]
Hi
No it's not showing an error.
When I open nvim, it just launches as plain neovim without loading the configs.

**Comment by adityastomar67** [comment]
Did you installed packer correctly.... Check it with running :packersync

**Comment by esperaking81** [comment]
I have another config working with packer properly.

**Comment by adityastomar67** [comment]
Did you placed it at right path? First move the previous config as backup then you have to resync your plugins as there is already cached plugins from your setup

**Comment by esperaking81** [comment]
I even tried to remove the nvim cache folder before.
I have many configs in my ./config
I can't just replace the whole .config folder. What I do is that I clone your nvim and mv my config to something like nvim.backup

**Comment by adityastomar67** [comment]
Try to run this config in container or some sort of virtual machine, in this way you'll be sure if the problem still occurs or not. Or you can create temporary HOME directory try to use that for checking this config.
In both the ways you'll be getting the actual problem.

If you don't know how to create temporary HOME directory, then go to my dotfiles repo, there the steps are clearly explained.

**Comment by adityastomar67** [comment]
The problem is resolved with the config and it can install the plugins automatically now.
