### ISSUE TITLE
Cursor animation plugin

### ISSUE THREAD

**Issue by liketoeatcheese** [adityastomar67/NvStar#4]
Hey mate,

First of all, awesome dot files!!

This is not a bug but a question. I saw the animation of the cursor and really intrigued. I went through all your packer plugins but didn't see any plugin with that animation set-up. How do you make the cursor move smoothly like that?

**Comment by adityastomar67** [comment]
Hey, first of all thanks for the appreciation. And the animations comes from the [plugin](https://github.com/psliwka/vim-smoothie). The plugin is placed in packer config file.

**Comment by liketoeatcheese** [comment]
Ummm, it's not the scrolling. I meant the animation from the cursor when you move up, down, left, right with jkhl. I tried the smoothies plugin but it only have animation when I <C-D> or <C-F>

**Comment by adityastomar67** [comment]
Can you please provide some more information on the same, I don't get what you ar asking for.

**Comment by liketoeatcheese** [comment]
Ah sorry, yea that was the plugin :) Thanks for the prompt reply
